# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Home"
  url = "#0_about"
  weight = 10

[[main]]
  name = "News"
  url = "#01_news"
  weight = 20

[[main]]
  name = "Experience"
  url = "#2_experience"
  weight = 30

[[main]]
  name = "Publications"
  url = "#3_publications"
  weight = 40

[[main]]
  name = "Awards"
  url = "#5_awards"
  weight = 50

[[main]]
  name = "Accomplishments"
  url = "#6_accomplishments"
  weight = 60

[[main]]
  name = "Side Projects"
  url = "#4_projects"
  weight = 70

[[main]]
  name = "CV"
  url = "media/Futa_Waseda_CV_20260210.pdf"
  weight = 80

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/media/resume.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "media/resume.pdf"
#    weight = 70
